name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, ubuntu-20.04]
    env:
      PYTHON_VERSION: 3.6.11
    steps:
    - uses: actions/checkout@v2
    - name: setup virtual environment
      run: |
        make setup
    - name: check python version
      run: |
        source activate.sh
        python -c "import platform; assert platform.python_version() == \"${PYTHON_VERSION}\""
    - name: check test target
      run: |
        make test
        source activate.sh
        pytest --version
    - name: check clean target
      run: |
        make clean
