name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, ubuntu-20.04]
    env:
      PYTHON_VERSION: 3.6.11
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      working-directory: ./tests
      run: |
        make -f Makefile.test setup
    - name: Run Tests
      working-directory: ./tests
      run: |
        make -f Makefile.test test
    - name: Check Black Formatting
      working-directory: ./tests
      run: |
        make -f Makefile.test black
    - name: Check clean target
      working-directory: ./tests
      run: |
        make -f Makefile.test clean
